import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"


const geistSans = Geist({
  variable: "--geist-font, -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--geist-font, -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}

